# creation rules are evaluated sequentially, the first match wins
creation_rules:
  # upon creation of a file that matches the pattern *dev.yaml,
  # KMS set A is used
  # eGOV Internal ------------------------------------------------------------------------------------------------------------- #
  # - path_regex: environments/azure-congo-uat-secrets.yaml$
  #   azure_keyvault: "https://congo-uat.vault.azure.net/keys/congo-uat/f55657aa499544dc832882c9cb4f3250"
  # - path_regex: environments/azure-congo-prod-secrets.yaml$
  #   azure_keyvault: "https://congo-uat.vault.azure.net/keys/congo-uat/f55657aa499544dc832882c9cb4f3250"

  - path_regex: ../environments/azure-congo-prod-secrets.yaml$
    azure_keyvault: "https://congo-prod.vault.azure.net/keys/congo-prod/7165be314bb046699c13ed62d68866ce"